detect:
  # GPU numbers
  num_gpus: 1
  num_types: 1
  # Network params for all camera types
  cam_0:
    # data file for darknet

    data_file: "/home/daiz/Data/demo715/demo.data"
    # cfg file for darknet
    test_cfg: "/home/daiz/Data/demo715/yolov3-tiny.cfg"
    test_weights: "/home/daiz/Data/demo715/yolov3-tiny/yolov3-tiny_last.weights"

    # data_file: "/home/daiz/Repo/darknet/cfg/coco.data"
    # # cfg file for darknet
    # test_cfg: "/home/daiz/Repo/darknet/cfg/yolov3-tiny.cfg"
    # test_weights: "/home/daiz/Data/yolov3-tiny.weights"

show_gui: true
